version: '2'
services:
  drupaldb:
    image: "mariadb"
    container_name: drupaldb
    volumes:
      - ${DB_PATH}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      DB_PATH: '${DB_PATH}'
    networks:
      - drupal
    restart: always
  drupal:
    # Pull directly from Dockerhub
    image: "ankitjain28/php-nginx-composer:latest"
    # build: ./docker/php-nginx-composer/
    # image: "php-nginx-composer"
    container_name: drupal
    ports:
      - "${APP_PORT}:80"
      - "8028:22"
    environment:
      APP_PORT: '${APP_PORT}'
    volumes:
      # - .:/var/www/html
      - drupal-sync:/var/www/html:nocopy
    links:
      - "drupaldb:mysql"
    networks:
      - drupal
    restart: always

volumes:
  drupal-sync:
    external: true
networks:
  drupal:
