---

- name: Deleting drupaldb container
  command: docker rm drupaldb -f

- name: Recreating drupaldb container
  command: docker-composer up -d drupaldb
  async: 1000
  poll: 10
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"

- name: Restarting Drupal Container
  command: docker restart drupal
