language: php
dist: trusty
sudo: required

services:
  - docker

php:
  - 7.2

# env:
#   global:
#     - SIMPLETEST_DB=sqlite://tmp/site.sqlite
#     - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
#   matrix:
#     - RELEASE=stable COMPOSER_CHANNEL=stable
#     - RELEASE=dev COMPOSER_CHANNEL=stable
#     - RELEASE=stable COMPOSER_CHANNEL=snapshot
env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update

  # Now we can install the newer docker-engine which is required for the newer
  # docker-composer we will install next. The messy options are to force it to
  # be non-interactive (normally it asks you a bunch of config questions).
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker-compose --version

  # As of the writing of this script Travis has docker-compose v1.4.2, we need
  # to update it to 1.8+. $DOCKER_COMPOSE_VERSION is provide from the `env`
  # above.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Check that docker-compose is now running the latest version (or at least the
  # one we specified). This is not to be confused with the version we printed
  # before doing the update.
  - docker-compose --version

install:
  - docker-compose up -d

# script:
#   - if [[ $RELEASE = dev ]]; then composer --verbose remove --no-update drupal/console; fi;
#   - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.6.x-dev webflo/drupal-core-require-dev:8.6.x-dev; fi;
#   - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
#   - cd $TRAVIS_BUILD_DIR/web
#   - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
#   - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
#   - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
#   # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
#   # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
#   - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
#   - ./../vendor/bin/drush
#   - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
