version: '2'
services:
  drupal:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: php-nginx-composer
    container_name: drupal
    ports:
      - "80:80"
      - "8028:22"
    volumes:
      - .:/var/www/html
    links:
      - "drupaldb:mysql"
    networks:
      - drupal
    restart: always
  drupaldb:
    image: "mariadb"
    container_name: drupaldb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db-dump:/var/www/html/db-dump
      - ./db-dump:/docker-entrypoint-initdb.d
    networks:
      - drupal
    restart: always

volumes:
  db:
networks:
  drupal:


