version: '2'
services:
    php:
        build:
          context: ./docker/webserver
          dockerfile: Dockerfile
        image: php-server
        restart: always
        volumes:
          - .:/var/www/html
        depends_on:
          - db
        links:
          - db:db
        networks:
          - nginxphp
    db:
        image: "mysql"
        ports:
          - "3306:3306"
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        networks:
          - nginxphp

volumes:
  db:
networks:
  nginxphp:
driver: local

