version: '2'
services:
  drupal:
    image: "ankitjain28/php-nginx-composer:latest"
    container_name: drupal
    ports:
      - "${PORT}:80"
      - "8028:22"
    volumes:
      - .:/var/www/html
    links:
      - "drupaldb:mysql"
    networks:
      - drupal
    restart: always
  drupaldb:
    image: "mariadb"
    container_name: drupaldb
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./db-dump:/var/www/html/db-dump
      - ./db-dump:/docker-entrypoint-initdb.d
    networks:
      - drupal
    restart: always

volumes:
  db:
networks:
  drupal:


