version: '2'
services:
    d8-php:
        build:
          context: ./docker/webserver
          dockerfile: Dockerfile
        image: php-server
        container_name: d8-php
        volumes:
          - .:/var/www/html
        links:
          - d8-db
        networks:
          - nginxphp
        restart: always
    d8-db:
        image: "mysql"
        container_name: d8-db
        ports:
          - "3306:3306"
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        networks:
          - nginxphp
        restart: always

volumes:
  db:
networks:
  nginxphp:


