version: '2'
services:
    web:
        image: nginx
        volumes:
            - ./docker/webserver/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build:
          context: ./docker/webserver
          dockerfile: Dockerfile
        image: php-server
        restart: always
        volumes:
            - .:/var/www/html
    db:
        image: "mysql"
        ports:
          - "3306:3306"
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret

volumes:
  db:

