version: '2'
services:
    drupal:
        build:
          context: ./docker/webserver
          dockerfile: Dockerfile
        image: php-server
        container_name: drupal
        ports:
          - "80:80"
          - "8028:22"
        volumes:
          - .:/var/www/html
        links:
          - "drupalmysql:mysql"
        networks:
          - nginxphp
        restart: always
    drupalmysql:
        image: "mariadb"
        container_name: drupalmysql
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        volumes:
          - ./db-dump:/docker-entrypoint-initdb.d
        networks:
          - nginxphp
        restart: always

volumes:
  db:
networks:
  nginxphp:


