---

- name: Cloning Github Stage branch branch name - "{{staging_branch}}" in {{project_dir}}/{{project_folder_name}} dir
  git:
    repo: "{{github_repo}}"
    dest: "{{project_dir}}/{{project_folder_name}}"
    version: "{{staging_branch}}"
    accept_hostkey: yes

- name: Adding Git Hooks on Commit
  command: mv ./.githooks/pre-commit ./.git/hooks/pre-commit