---

- name: Clone Github Stage branch branch name - "{{staging_branch}}"
  git:
    repo: "{{github_repo}}"
    dest: "{{project_dir}}/{{project_folder_name}}"
    version: "{{staging_branch}}"
    accept_hostkey: yes