---

- name: stat backup
  stat:
    path: "{{backup_dir}}/{{backup_folder_name}}"
  register: backup_stat

- name: Delete previous backup
  command: rm -r "{{backup_folder_name}}"
  when: backup_stat.stat.exists
  args:
    chdir: "{{backup_dir}}"

- name: stat html
  stat:
    path: "{{project_dir}}/{{project_folder_name}}"
  register: html_stat

- name: Move html to backup
  command: mv {{project_dir}}/{{project_folder_name}}
    {{backup_dir}}/{{backup_folder_name}}
  when: html_stat.stat.exists

- name: Create html dir
  command: mkdir {{project_folder_name}}
  args:
    chdir: "{{project_dir}}"
