---

- name: Import Configuration
  command: docker exec drupal composer drupal ci
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"

- name: Rebuild Cache
  command: docker exec drupal composer drupal cr
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"