---

- name: Importing Configuration
  command: docker exec drupal composer drupal ci
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"

- name: Rebuilding Cache
  command: docker exec drupal composer drupal cr
  args:
    chdir: "{{project_dir}}/{{project_folder_name}}"